"""add unique constraint to student courses

Revision ID: f147fd4a8280
Revises: f54236bc5fd4
Create Date: 2026-09-24 09:35:30.804702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f147fd4a8280'
down_revision: Union[str, Sequence[str], None] = 'f54236bc5fd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_student_course', 'student_courses', ['student_id', 'course_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_student_course', 'student_courses', type_='unique')
    # ### end Alembic commands ###
