"""add student course junction table

Revision ID: f54236bc5fd4
Revises: 0f61addcbd5d
Create Date: 2026-09-23 16:43:26.113131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f54236bc5fd4'
down_revision: Union[str, Sequence[str], None] = '0f61addcbd5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('students_course_id_fkey'), 'students', type_='foreignkey')
    op.drop_column('students', 'course_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('students_course_id_fkey'), 'students', 'courses', ['course_id'], ['id'])
    op.drop_table('student_courses')
    # ### end Alembic commands ###
